/*
 * File: app/view/PanelSearch.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PanelSearch', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.panelsearch',

    stateful: true,
    height: 464,
    layout: {
        type: 'absolute'
    },
    title: 'Employee Information',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 539,
                    layout: {
                        type: 'absolute'
                    },
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            x: 70,
                            y: 10,
                            width: 220,
                            fieldLabel: 'Employee Name',
                            labelAlign: 'top',
                            name: 'EmployeeName',
                            emptyText: 'Type for hints..'
                        },
                        {
                            xtype: 'combobox',
                            x: 1040,
                            y: 10,
                            width: 220,
                            fieldLabel: 'Include',
                            labelAlign: 'top',
                            name: 'Include'
                        },
                        {
                            xtype: 'combobox',
                            x: 700,
                            y: 10,
                            width: 240,
                            fieldLabel: 'Employment Status',
                            labelAlign: 'top',
                            name: 'EmploymentStatus',
                            emptyText: 'All'
                        },
                        {
                            xtype: 'textfield',
                            x: 380,
                            y: 10,
                            width: 230,
                            fieldLabel: 'Id',
                            labelAlign: 'top',
                            name: 'Id',
                            emptyText: 'Type Employee Id...'
                        },
                        {
                            xtype: 'textfield',
                            x: 70,
                            y: 70,
                            width: 220,
                            fieldLabel: 'Supervisor Name',
                            labelAlign: 'top',
                            name: 'SupervisorName',
                            emptyText: 'Type for hints..'
                        },
                        {
                            xtype: 'combobox',
                            x: 380,
                            y: 70,
                            width: 230,
                            fieldLabel: 'Job Title',
                            labelAlign: 'top',
                            name: 'JobTitle'
                        },
                        {
                            xtype: 'combobox',
                            x: 700,
                            y: 70,
                            width: 240,
                            fieldLabel: 'Sub Unit',
                            labelAlign: 'top',
                            name: 'SubUnit'
                        },
                        {
                            xtype: 'button',
                            x: 70,
                            y: 150,
                            height: 30,
                            width: 90,
                            text: 'Search'
                        },
                        {
                            xtype: 'button',
                            x: 200,
                            y: 150,
                            height: 30,
                            width: 90,
                            text: 'Reset'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});